### ISSUE TITLE
关于远程端口的问题

### ISSUE THREAD

**Issue by tabris-trees** [xiongyu/hexowriter#1]
大佬太强了，如果使用的是hexo加GitHub page的话远程端口使用GitHub的端口吗？

**Comment by xiongyu** [comment]
sorry, 我写这个插件完全没考虑过github page, 所以..是用不了的。不过你也提醒了我，我会在下一个版本加上github page的支持。

**Comment by tabris-trees** [comment]
哦哦，好的，谢谢大佬！！！
